services:
db:
  image: postgres:16
  environment:
  POSTGRES_DB : platformEtudiant
  POSTGRES_USER : admin
  POSTGRES_PASSWORD : $(DB_PASSWORD_LINUX)
  volumes:
  - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  - pgdata:/var/lib/postgres/data
  ports:
  - 5432:5432
